kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd
spec:
  args:
        - name: baseline-ns
        - name: preview-ns
  metrics:
    - name: isd
      count: 1
      initialDelay: 45s
      provider:
        opsmx:
          application: multins-bg
          user: admin
          lifetimeMinutes: 10
          threshold:
            pass: 80
            marginal: 60
          services:

          - serviceName: oes-audit-client
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-audit-client.*"
            canaryMetricScope: "{{args.preview-ns}},oes-audit-client.*"
          - serviceName: oes-audit-service
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-audit-service.*"
            canaryMetricScope: "{{args.preview-ns}},oes-audit-service.*"
          - serviceName: oes-autopilot
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-autopilot.*"
            canaryMetricScope: "{{args.preview-ns}},oes-autopilot.*"
          - serviceName: oes-dashboard
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-dashboard.*"
            canaryMetricScope: "{{args.preview-ns}},oes-dashboard.*"
          - serviceName: oes-datascience
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-datascience.*"
            canaryMetricScope: "{{args.preview-ns}},oes-datascience.*"
          - serviceName: oes-gate
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-gate.*"
            canaryMetricScope: "{{args.preview-ns}},oes-gate.*"
          - serviceName: oes-platform
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-platform.*"
            canaryMetricScope: "{{args.preview-ns}},oes-platform.*"
          - serviceName: oes-sapor
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-sapor.*"
            canaryMetricScope: "{{args.preview-ns}},oes-sapor.*"
          - serviceName: oes-ui
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-ui.*"
            canaryMetricScope: "{{args.preview-ns}},oes-ui.*"
          - serviceName: oes-visibility
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v1.0"
            metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "{{args.baseline-ns}},oes-visibility.*"
            canaryMetricScope: "{{args.preview-ns}},oes-visibility.*"
